const mockDetailsFilms = [
  {
    'id': 'movie-1',
    'previewImage': 'images/posters/the-great-flamarion.jpg',
    'title': 'driver copying',
    'year': 1990,
    'duration': 30,
    'genre': 'Horror',
    'description': 'Eos rerum voluptatem nam quia sit in cumque quam labore. Occaecati quo nisi repellat voluptas nesciunt. Sit ullam a et exercitationem autem consectetur consequatur et consequuntur. Soluta est quidem est aut sapiente. Sequi deleniti commodi. Id sit qui veniam nostrum aliquid deleniti eos necessitatibus.',
    'rating': 5.3,
    'isFavorite': false,
    'top': true,
    'ageRating': 18,
    'director': 'No name',
    'actors': ['actor', 'actors2', 'actors3', 'actors4'],
    'genres': ['Horror', 'Thriller'],
    'writers': ['Writers1', 'Writers2', 'Writers3', 'Writers4'],
  },
  {
    'id': 'movie-2',
    'previewImage': 'images/posters/made-for-each-other.png',
    'title': 'Keyboard IB',
    'year': 2019,
    'duration': 138,
    'genre': 'Horror',
    'description': 'Ratione consectetur in minima consequuntur vero labore quas. Suscipit voluptatum dicta distinctio ea ipsa recusandae doloremque qui. Qui repudiandae qui cumque rerum quia ipsam. Est blanditiis doloremque dolorem quos id voluptatem voluptate. At commodi occaecati vero.',
    'rating': 3.3,
    'isFavorite': false,
    'top': false,
    'ageRating': 16,
    'director': 'No name',
    'actors': ['actor', 'actors2', 'actors3', 'actors4'],
    'genres': ['Horror', 'Thriller'],
    'writers': ['Writers1', 'Writers2', 'Writers3', 'Writers4'],
  },
  {
    'id': 'movie-3',
    'previewImage': 'images/posters/santa-claus-conquers-the-martians.jpg',
    'title': 'backing open-source',
    'year': 1989,
    'duration': 73,
    'genre': 'Drama',
    'description': 'Asperiores fuga quaerat. Officiis cupiditate soluta iste dolores rerum. Sint unde tenetur ipsum dolorum dolores natus magni praesentium. Magni nemo consequatur ratione quisquam ut. Voluptas debitis omnis. Fugiat et in et esse quo reiciendis.',
    'rating': 8.3,
    'isFavorite': false,
    'top': false,
    'ageRating': 16,
    'director': 'No name',
    'actors': ['actor', 'actors2', 'actors3', 'actors4'],
    'genres': ['Horror', 'Thriller'],
    'writers': ['Writers1', 'Writers2', 'Writers3', 'Writers4'],
  },
  {
    'id': 'movie-4',
    'previewImage': 'images/posters/popeye-meets-sinbad.png',
    'title': 'Fresh Ridges',
    'year': 2003,
    'duration': 98,
    'genre': 'Horror',
    'description': 'Est officia quas autem. Aut iste eaque sunt ut similique nam expedita architecto et. Omnis debitis porro aliquid dolor unde non laboriosam. Nisi sed earum ut.',
    'rating': 6.5,
    'isFavorite': false,
    'top': false,
    'ageRating': 16,
    'director': 'No name',
    'actors': ['actor', 'actors2', 'actors3', 'actors4'],
    'genres': ['Horror', 'Thriller'],
    'writers': ['Writers1', 'Writers2', 'Writers3', 'Writers4'],
  },
  {
    'id': 'movie-5',
    'previewImage': 'images/posters/made-for-each-other.png',
    'title': 'Licensed Turkey',
    'year': 2018,
    'duration': 91,
    'genre': 'Sci-Fi',
    'description': 'Nostrum fugiat qui praesentium et aut molestias distinctio aut. Repellendus nihil dolor nostrum rem ea sed illo. Deleniti eligendi reiciendis. Sed enim rem pariatur non quas neque. Eos iusto quisquam amet aut quasi excepturi esse doloremque. Labore eum vitae quos.',
    'rating': 1.4,
    'isFavorite': false,
    'top': false,
    'ageRating': 16,
    'director': 'No name',
    'actors': ['actor', 'actors2', 'actors3', 'actors4'],
    'genres': ['Horror', 'Thriller'],
    'writers': ['Writers1', 'Writers2', 'Writers3', 'Writers4'],
  },
  {
    'id': 'movie-6',
    'previewImage': 'images/posters/popeye-meets-sinbad.png',
    'title': 'Polynesia Washington',
    'year': 2014,
    'duration': 180,
    'genre': 'Comedy',
    'description': 'Odio beatae nam et nam repellat voluptatem dolores quisquam voluptas. Repudiandae aperiam officiis. Molestiae est quidem quis autem totam est iste quia soluta. Quisquam ut veniam consectetur illum veniam odit illo. Temporibus officia qui sit omnis quas dolorem reiciendis doloremque est.',
    'rating': 8.8,
    'isFavorite': false,
    'top': false,
    'ageRating': 16,
    'director': 'No name',
    'actors': ['actor', 'actors2', 'actors3', 'actors4'],
    'genres': ['Horror', 'Thriller'],
    'writers': ['Writers1', 'Writers2', 'Writers3', 'Writers4'],
  },
  {
    'id': 'movie-7',
    'previewImage': '../../../public/images/posters/sagebrush-trail.jpg',
    'title': 'local Chicken',
    'year': 2023,
    'duration': 130,
    'genre': 'Comedy',
    'description': 'Accusantium similique voluptatum quisquam nesciunt. Dolores voluptas commodi alias. Repellat eum voluptatum earum et pariatur et. Consequuntur neque esse provident eum totam ut. Voluptatum laborum nihil officia corporis est. Quaerat reprehenderit voluptatem perspiciatis qui ut sapiente iusto totam sequi.',
    'rating': 6.9,
    'isFavorite': false,
    'top': false,
    'ageRating': 16,
    'director': 'No name',
    'actors': ['actor', 'actors2', 'actors3', 'actors4'],
    'genres': ['Horror', 'Thriller'],
    'writers': ['Writers1', 'Writers2', 'Writers3', 'Writers4'],
  },
  {
    'id': 'movie-8',
    'previewImage': '../../../public/images/posters/made-for-each-other.png',
    'title': 'Toys Ball',
    'year': 1986,
    'duration': 150,
    'genre': 'Comedy',
    'description': 'Saepe facilis culpa natus ipsa. Molestiae voluptates minus consequatur a quia est sed. Temporibus vero est consectetur. Itaque sint culpa quos quo optio in sit omnis. Blanditiis non cumque eos.',
    'rating': 4.2,
    'isFavorite': false,
    'top': false,

    'ageRating': 16,
    'director': 'No name',
    'actors': ['actor', 'actors2', 'actors3', 'actors4'],
    'genres': ['Horror', 'Thriller'],
    'writers': ['Writers1', 'Writers2', 'Writers3', 'Writers4'],
  },
  {
    'id': 'movie-9',
    'previewImage': '../../../public/images/posters/sagebrush-trail.jpg',
    'title': 'parsing Savings',
    'year': 2001,
    'duration': 71,
    'genre': 'Drama',
    'description': 'Laboriosam quo alias beatae ut. Delectus sapiente libero. Non molestiae sed voluptatum autem. Similique culpa doloremque qui molestias dolorem sint eligendi.',
    'rating': 6.7,
    'isFavorite': false,
    'top': false,
    'ageRating': 16,
    'director': 'No name',
    'actors': ['actor', 'actors2', 'actors3', 'actors4'],
    'genres': ['Horror', 'Thriller'],
    'writers': ['Writers1', 'Writers2', 'Writers3', 'Writers4'],
  },
  {
    'id': 'movie-10',
    'previewImage': 'images/posters/interstellar.webp',
    'title': 'Интерстеллар',
    'year': 2014,
    'duration': 220,
    'genre': 'fantastic',
    'description': 'Когда засуха, пыльные бури и вымирание растений приводят человечество к продовольственному кризису, коллектив исследователей и учёных отправляется сквозь червоточину (которая предположительно соединяет области пространства-времени через большое расстояние) в путешествие, чтобы превзойти прежние ограничения для космических путешествий человека и найти планету с подходящими для человечества условиями.',
    'rating': 9.1,
    'isFavorite': false,
    'top': true,
    'ageRating': 18,
    'director': 'No name',
    'actors': ['actor', 'actors2', 'actors3', 'actors4'],
    'genres': ['Horror', 'Thriller'],
    'writers': ['Writers1', 'Writers2', 'Writers3', 'Writers4'],
  },
  {
    'id': 'new-movie-1',
    'previewImage': '../../public/images/posters/kentavr.webp',
    'title': 'The centaur',
    'year': 2023,
    'duration': 165,
    'genre': 'Triller',
    'description': 'Беззащитная девушка оказывается самой опасной пассажиркой ночного таксиста. Виртуозный триллер с Юрой Борисовым',
    'rating': 7.8,
    'isFavorite': false,
    'top': true,
    'ageRating': 16,
    'director': 'No name',
    'actors': ['actor', 'actors2', 'actors3', 'actors4'],
    'genres': ['Horror', 'Thriller'],
    'writers': ['Writers1', 'Writers2', 'Writers3', 'Writers4'],
  },
  {
    'id': 'new-movie-2',
    'previewImage': '../../public/images/posters/lady-bag.webp',
    'title': 'Lady bug and super cat',
    'year': 2023,
    'duration': 165,
    'genre': 'cartoon',
    'description': 'Влюбленные подростки-супергерои спасают Париж. Самый романтичный мультсериал о борьбе добра со злом',
    'rating': 8.7,
    'isFavorite': false,
    'top': true,
    'ageRating': 16,
    'director': 'No name',
    'actors': ['actor', 'actors2', 'actors3', 'actors4'],
    'genres': ['Horror', 'Thriller'],
    'writers': ['Writers1', 'Writers2', 'Writers3', 'Writers4'],
  },
  {
    'id': 'new-movie-3',
    'previewImage': '../../public/images/posters/home-alone.webp',
    'title': 'Home alone',
    'year': 1990,
    'duration': 165,
    'genre': 'comedy',
    'description': 'Американское семейство отправляется из Чикаго в Европу, но в спешке сборов бестолковые родители забывают дома... одного из своих детей. Юное создание, однако, не теряется и демонстрирует чудеса изобретательности. И когда в дом залезают грабители, им приходится не раз пожалеть о встрече с милым крошкой.',
    'rating': 8.3,
    'isFavorite': false,
    'top': true,
    'ageRating': 16,
    'director': 'No name',
    'actors': ['actor', 'actors2', 'actors3', 'actors4'],
    'genres': ['Horror', 'Thriller'],
    'writers': ['Writers1', 'Writers2', 'Writers3', 'Writers4'],
  },
  {
    'id': 'new-movie-4',
    'previewImage': '../../public/images/posters/three-cats.webp',
    'title': 'three-cats',
    'year': 2015,
    'duration': 1150,
    'genre': 'cartoon',
    'description': 'Озорные котята любят игры и сладости, а уборку и кашу — не очень. Забавные сюжеты из жизни многодетной семьи',
    'rating': 8.2,
    'isFavorite': false,
    'top': true,
    'ageRating': 16,
    'director': 'No name',
    'actors': ['actor', 'actors2', 'actors3', 'actors4'],
    'genres': ['Horror', 'Thriller'],
    'writers': ['Writers1', 'Writers2', 'Writers3', 'Writers4'],
  },
  {
    'id': 'new-movie-4',
    'previewImage': '../../../public/images/posters/made-for-each-other.png',
    'title': 'Licensed Turkey',
    'year': 2018,
    'duration': 91,
    'genre': 'Sci-Fi',
    'description': 'Nostrum fugiat qui praesentium et aut molestias distinctio aut. Repellendus nihil dolor nostrum rem ea sed illo. Deleniti eligendi reiciendis. Sed enim rem pariatur non quas neque. Eos iusto quisquam amet aut quasi excepturi esse doloremque. Labore eum vitae quos.',
    'rating': 1.4,
    'isFavorite': false,
    'top': false,
    'ageRating': 16,
    'director': 'No name',
    'actors': ['actor', 'actors2', 'actors3', 'actors4'],
    'genres': ['Horror', 'Thriller'],
    'writers': ['Writers1', 'Writers2', 'Writers3', 'Writers4'],
  },

];

export { mockDetailsFilms };
